import React from 'react';
import {Card} from "antd";
class Defination extends React.Component{
    render(){
        return (
            <Card className="bg-light font-weight-bolder" title="What Is Bioinformatics ?" style={{ maxHeigth: 300 }}>
                <div  style={{maxHeight:500,overflowY:'auto',overflowX:'hidden'}}>
                    The prime means for healing in medicine is pharmaceuticals. Pharmaceuticals contain chemical entities – “drugs” – that interact in specific ways with the cells in the body and thereby alter the cell processes in desired ways to improve or cure a disease condition.
                    However, developing new drugs and understanding the functions of them are very difficult and challenging tasks. One reason is that there exist very many compounds that potentially can be used as drugs. Theoretically one could synthesize 1060 compounds that are “drug-like”. This is an astronomic number that can actually never be realized. Compare this number with age of the universe, which is “only” 1022 seconds! Developing drugs successfully therefore means “putting the money on the right horse”. In other words we need to select the good candidates from the 1060 possibilities, and this preferably even before we synthesize and evaluate any of them experimentally. Another reason for the difficulty is that a lot of different and often quite contradictory properties need to be tailored into one single chemical molecule. This includes proper uptake and distribution of the drug, and good safety and efficiency on the disease conditions to be treated. Again how can we know beforehand which compound of all the 1060 possibilities that combines all these properties in the best way?
                    To design a new therapy and make a new drug we need to understand the intricate details of the cells; how the components of the cell interact with each other and how they react to foreign molecules like drugs. These are very challenging tasks, but the genomics revolution has given us enormous possibilities to reveal all the intricate details. This includes methods for massive gene sequencing, platforms for large-scale gene expression analysis, proteomics analysis systems, automated methods for chemical synthesis, and high throughput robots for screening of drug candidates.
                    However, making an intelligent use of the massive amounts of data created by the genomics revolution is a daunting task. Without proper analysis tools important discoveries and understandings risk to be literally drained away in the floods of data created by all the technologies brought about by the genomics revolution.
                    So how can we know what function to target in the body to create an effective therapy or a new drug? How can we know which chemical to select as the good pharmaceutical that cures a disease from the myriads of possible compounds without needed to test billions of chemicals randomly and waste all our resources on useless compounds? It is here that pharmaceutical bioinformatics comes in! New ingenious computational and informatics methods have been developed and are in constant development. This includes new methods in computational chemistry, computational approaches in systems biology, bioinformatics and cheminformatics, all of which can aid our understanding of the functions body and the drug discovery processes tremendously. Pharmaceutical bioinformatics deals with how to use and cross-use such information effectively. It includes mapping the functions of the organisms and it deals with how to design new chemical entities that interact with the organism in the desired ways. It deals with how to design new therapies and how to apply them in the most effective way. All of this is collected and taught in the new discipline of pharmaceutical bioinformatics.
                    In short pharmaceutical bioinformatics is the broad scientific area of computer based technologies and informatics and computational methods that intermingles with all areas related to the discovery and development drugs, for understanding their functions, and all the novel and important computational and computer based tools for mapping processes of the cells and understanding how to use these properties to effectively develop novel drugs.
                </div>
            </Card>
        )
    }
}
export default Defination;